import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to {' '}
          <span className={styles.logo}>
            <Image src="/roi-logo.png" alt="Roi Logo" width={200} height={60} />
          </span>
        </h1>

        <div className={styles.grid}>
          <Link href="/jobs">
            <a className={styles.card}>
              <h2>Jobs &rarr;</h2>
              <p>Move to jobs page.</p>
            </a>
          </Link>

          <Link href="/apply">
            <a className={styles.card}>
              <h2>Apply &rarr;</h2>
              <p>Move to apply page.</p>
            </a>
          </Link>
          
          <Link href="/job">
            <a className={styles.card}>
              <h2>Job &rarr;</h2>
              <p>Move to Job page.</p>
            </a>
          </Link>
          
          <Link href="/apply-job">
            <a className={styles.card}>
              <h2>Apply Job &rarr;</h2>
              <p>Move to apply job page.</p>
            </a>
          </Link>
          
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://roi-ai.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/roi-logo.png" alt="Roi Logo" width={50} height={20} />
          </span>
        </a>
      </footer>
    </div>
  )
}
